version: '2'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - '9000:80'
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_USER: 'wp_user'
      WORDPRESS_DB_PASSWORD: 'database_password'
    # env_file: .env
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.7
    # env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wp_user'
      MYSQL_PASSWORD: 'database_password'
    volumes:
      - db-data:/var/lib/mysql

# database用にストレージの永続化設定
volumes:
  db-data:
